;1、域名组
ruleset=🔍 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=👽 AI US,https://raw.githubusercontent.com/szkane/ClashRuleSet/refs/heads/main/Clash/Ruleset/AiDomain.list
ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list
ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Proxy.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=➡️ 国内,[]FINAL

;2、策略组（域名组-节点组）
custom_proxy_group=🔍 Google`select`[]DIRECT`[]🇭🇰香港`[]🇺🇸美国
custom_proxy_group=👽 AI US`select`[]DIRECT`[]🇭🇰香港`[]🇺🇸美国
custom_proxy_group=🌍 国外`select`[]DIRECT`[]🇭🇰香港`[]🇺🇸美国
custom_proxy_group=➡️ 国内`select`[]DIRECT`[]🇭🇰香港`[]🇺🇸美国

;3、节点组
custom_proxy_group=🇭🇰香港`select`(香港|HK|Hong Kong|🇭🇰|HongKong)
custom_proxy_group=🇺🇸美国`select`(广美|美|US|纽约|波特兰|达拉斯|俄勒|凤凰城|费利蒙|硅谷|拉斯|洛杉|圣何塞|圣克拉|西雅|芝加|🇺🇸|United States)

;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
